### ISSUE TITLE
Missing something fundamental when try to remove demo user

### ISSUE THREAD

**Issue by weisisheng** [MrHertal/react-admin-amplify#76]
1. If I comment out the authProvider.getIdentity section in App.js, I get the error,
 
LoginForm.js:36 Uncaught (in promise) TypeError: Cannot destructure property 'username' of 'userData.data.getUser' as it is null.
    at getDemoUser (LoginForm.js:36:1)

and no fields for username/password render.

----

2. If I comment out the 'getDemoUser()' and if(!demoUser) return null sections in LoginForm.js, I get a username/password field which then errors to
 
 'TypeError: Cannot read properties of undefined (reading 'includes')
    at children (App.js:133:1)'.

Appreciate any assistance or words of wisdom. Thank you.

**Comment by weisisheng** [comment]
Moved to--> https://github.com/MrHertal/react-admin-amplify-demo/issues/56
